### PR TITLE
Handled Settings activity back button

### PR DESCRIPTION
**Pull request by LowTension**
Delete the .pngs for back button in your drawable folders.
Android adds back button for you.

### CODE REVIEW

**Comment by berkantkz** [comment]
What you did and what we did are actually the same thing. Only the way of initalizing it is different. 

Moreover, ```setSupportActionBar(Toolbar toolBar)``` and ```getSupportActionBar()``` functions are not available on ```PreferenceActivity```.

**Comment by LowTension** [comment]
is easy to solve:
```
getLayoutInflater().inflate(R.layout.action_bar), (ViewGroup)findViewById(android.R.id.content));
        Toolbar mToolbar = (Toolbar)findViewById(R.id.action_bar_tool);
        setSupportActionBar(mToolbar);
        if (getSupportActionBar() != null) {
            getSupportActionBar().setDisplayHomeAsUpEnabled(true);
            getSupportActionBar().setDisplayShowHomeEnabled(true);
        }
```

**Comment by berkantkz** [comment]
Well, thanks for the solution but it works well currently. So it is unnecessary for now. Thanks again!

**Comment by Dyneteve** [comment]
@ZonaRMR If you have free time it woud be better if you tried to update the app theme to MaterialDesign-Light

**Pull request closed without merging**
