### PR TITLE
Italian language for teh app

### PR DESCRIPTION
**Pull request by bovirus**
Add Italian language for app GUI

### CODE REVIEW

**Comment by berkantkz** [comment]
You also need to add "it" [here](https://github.com/TwrpBuilder/TwrpBuilder/blob/master/app/src/main/java/com/github/TwrpBuilder/app/SettingsActivity.java#L45) and add "Italian" [here](https://github.com/TwrpBuilder/TwrpBuilder/blob/master/app/src/main/java/com/github/TwrpBuilder/app/SettingsActivity.java#L53). 

Can you please make these changes as well?

Thanks for your help.

**Comment by bovirus** [comment]
@berkantkz 

Done. Thanks.

**Comment by amitkhairnar44** [comment]
The Travis CI build has failed.
Fix the errors before merging.
Check your strings.xml line no. 95 
@bovirus

**Comment by bovirus** [comment]
@amitkhairnar44 

Thanks for the help.
Typo error fixed.

**Comment by berkantkz** [comment]
Yep, I've seen @bovirus . It should be okay now @amitkhairnar44 .

**Comment by surendrajat** [comment]
Building error was due to older firebase libraries. Fixed now.

**Pull request merged**
