### PR TITLE
Enhanced Spanish(MX) translation

### PR DESCRIPTION
**Pull request by LowTension**
Spanish(MX) translated: 100%

### CODE REVIEW

**Comment by berkantkz** [comment]
Thanks for contributing to our project.

**Comment by LowTension** [comment]
You're welcome.

**Comment by berkantkz** [comment]
Can you please make updates according to the latest change @ZonaRMR?

**Comment by LowTension** [comment]
I don't see any changes for values-es-rMX

**Comment by berkantkz** [comment]
https://github.com/TwrpBuilder/TwrpBuilder/blob/3c1865c5511cba01a415280e014675841250ba68/app/src/main/res/values-it/array.xml

Add the same file as ```values-es-rMX``` and translate the values, please.

**Comment by LowTension** [comment]
Isn't necessary. I'm working on it.

**Pull request merged**
